name: app1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  file_picker: ^8.1.2
  flutter:
    sdk: flutter
  flutter_map: ^7.0.0
  google_maps_flutter: ^2.9.0
  latlong2: ^0.9.0
  firebase_core: ^3.6.0

  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
