// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3xnUmdMgBO0DlQUKh3w0KQmDNArnqQz8',
    appId: '1:306871972058:web:012f004bde5ac991b635e3',
    messagingSenderId: '306871972058',
    projectId: 'operarios-de-barrido',
    authDomain: 'operarios-de-barrido.firebaseapp.com',
    storageBucket: 'operarios-de-barrido.appspot.com',
    measurementId: 'G-221502Z1RR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXEhunQSDO05qWShxOPqqtFZ9sf0Q-cGc',
    appId: '1:306871972058:android:05d5bf5d22ac95fab635e3',
    messagingSenderId: '306871972058',
    projectId: 'operarios-de-barrido',
    storageBucket: 'operarios-de-barrido.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhm91UhSFR0OxWJs7WZ7fG62mhqQSRx4s',
    appId: '1:306871972058:ios:b28b33976409e0e6b635e3',
    messagingSenderId: '306871972058',
    projectId: 'operarios-de-barrido',
    storageBucket: 'operarios-de-barrido.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhm91UhSFR0OxWJs7WZ7fG62mhqQSRx4s',
    appId: '1:306871972058:ios:b28b33976409e0e6b635e3',
    messagingSenderId: '306871972058',
    projectId: 'operarios-de-barrido',
    storageBucket: 'operarios-de-barrido.appspot.com',
    iosBundleId: 'com.example.app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3xnUmdMgBO0DlQUKh3w0KQmDNArnqQz8',
    appId: '1:306871972058:web:02696ab590df1eb3b635e3',
    messagingSenderId: '306871972058',
    projectId: 'operarios-de-barrido',
    authDomain: 'operarios-de-barrido.firebaseapp.com',
    storageBucket: 'operarios-de-barrido.appspot.com',
    measurementId: 'G-F1D5HDWBB3',
  );
}
